---
title: "Figure3b_compare_binding_ratio"
output: html_document
date: "2025-01-13"
---


**Purpose:** Calculate binding ratio

**Methods:**

* Restrict to variants with a cancer cell fraction at or near 1 - testing 0.75 since this was used in the Westcott paper

## Libraries

```{r}
library(stringr)
library(ggplot2)
library(ggpubr)
library(biomaRt)
library(DGEobj.utils)
library(stringi)
```


## Read in clinical data
```{r}
clinical_data <- as.data.frame(read.csv("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/Metadata/Metadata_annotations_all_Mayo_samples.csv"))
clinical_data <- clinical_data[which(clinical_data$Include_in_study=="Yes"),]
clinical_data <- clinical_data[-which(is.na(clinical_data$Tumor_Sample_Barcode)),]
clinical_data <- clinical_data[-which(is.na(clinical_data$RNA_ID)),]
```


## Define functions for below
```{r}
# Define a function for reading in and processing netMHC files
process_netMHC <- function(file){
    netMHC_matrix <- as.data.frame(read.table(file, skip=1, header=TRUE))
    netMHC_matrix <- netMHC_matrix[,which(colnames(netMHC_matrix) %in% c("Peptide", "ID", "nM", "nM.1", "nM.2", "nM.3", 
                                              "nM.4", "nM.5"))]
    netMHC_matrix <- netMHC_matrix[-which(netMHC_matrix$Peptide %in% wt_all$V2),]
    netMHC_matrix <- netMHC_matrix[which(str_length(netMHC_matrix$Peptide) %in% c(9)),]
    #netMHC_matrix <- netMHC_matrix[-1,]
    netMHC_matrix <- unique(netMHC_matrix)
    ID <- str_split_fixed(netMHC_matrix$ID, "_", 4)
    ID[,1] <- paste("chr", ID[,1], sep="")
    netMHC_matrix$ID <- paste(ID[,1], ID[,2], sep=":")
    return(netMHC_matrix)
}
```

## Read expression in TPM

```{r}
expression_data <- as.data.frame(read.csv("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/RNA_seq/star/all_samples_tpm.counts.txt", row.names = 1))
colnames(expression_data) <- gsub("NPT.", "NPT-", colnames(expression_data))
colnames(expression_data) <- gsub("\\.1_", "-1_", colnames(expression_data))
colnames(expression_data) <- gsub("\\.2_", "-2_", colnames(expression_data))
#expression_data <- t(expression_data)
expression_data <- as.data.frame(expression_data)
human <- useMart("ensembl", dataset="hsapiens_gene_ensembl")
```

## Match binding and calculate TCR recognition potential
```{r}
for (k in 1:length(clinical_data$ID)){
  sample=clinical_data$ID[k]
  print(sample)
  if (!file.exists(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/Immunogenicity/", sample, "_peptides_kd_stab.txt", sep=""))){
  
  ## Read in patient peptides for matching characteristics
  peptides <- as.data.frame(read.table(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/MT_peptides/", sample, ".somaticvariants_filtered_vep.peptides", sep=""), header=FALSE))
  
  ## Read in cancer cell fraction
  CCF <- as.data.frame(read.csv(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/MAF_file/", clinical_data$ID[k], "_variants_CN.csv", sep="")))
  CCF$mutation_id <- paste(CCF$Chromosome, CCF$Start_Position-1, CCF$Reference_Allele, CCF$Tumor_Seq_Allele2, sep=":") # Format mutation ID
  CCF <- CCF[match(peptides$V5, CCF$mutation_id),] # Match to peptides
  identical(peptides$V5[101], CCF$mutation_id[101]) # Check identical (there are some NAs, so checking one index)
  peptides$CCF <- CCF$CCF # Assign CCF
  if (length(peptides[which(is.na(peptides$CCF)),7])>0){ # If there are NAs, remove them
    peptides <- peptides[-which(is.na(peptides$CCF)),]
  }
  
  ## Set up peptide ID for matching downstream
  ID <- str_split_fixed(peptides$V5, ":", 4)
  peptides$V5 <- paste(ID[,1], ID[,2], sep=":")
  peptides <- peptides[!duplicated(peptides$V6),]
  
  ## Match expression
  result <- getBM(attributes=c("ensembl_transcript_id", "hgnc_symbol"), filters = "ensembl_transcript_id", values = peptides$V2, mart= human)
  result <- result[match(peptides$V2, result$ensembl_transcript_id),]
  peptides$gene <- result$hgnc_symbol
  expression_matched <- expression_data[match(result$hgnc_symbol, rownames(expression_data)),]
  peptides$expression <- expression_matched[, which(colnames(expression_matched)==clinical_data$RNA_ID[k])]
  
  ## Read in wt results
  wt_all <- as.data.frame(read.csv(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/WT_peptides/", sample, ".WT_n_mers_9_10_15mer.peptides", sep=""), header=FALSE))
  
  ## Read in and format Kd results
  netMHC_matrix <- as.data.frame(read.table(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/", sample, "_netmhc_9_10mer.xsl", sep=""), skip=1, header=TRUE))
  netMHC <- netMHC_matrix[,which(colnames(netMHC_matrix) %in% c("Peptide", "ID", "nM", "nM.1", "nM.2", "nM.3", "nM.4", "nM.5"))]
  netMHC <- netMHC[-which(netMHC$Peptide %in% wt_all$V2),]
  netMHC <- unique(netMHC)
  ID <- str_split_fixed(netMHC$ID, "_", 4)
  ID[,1] <- paste("chr", ID[,1], sep="")
  netMHC$ID <- paste(ID[,1], ID[,2], sep=":")
  
  ## Read in and format Stab results
  netMHCstab <- as.data.frame(read.table(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCstabpan/", sample, "_netmhcstab_9_10mer.xsl", sep=""), skip=1, header=TRUE))
  netMHCstab <- netMHCstab[,which(colnames(netMHCstab) %in% c("Peptide", "ID", "Thalf.h.", "Thalf.h..1", "Thalf.h..2", "Thalf.h..3", "Thalf.h..4", "Thalf.h..5"))]
  netMHCstab <- netMHCstab[match(netMHC_matrix$Peptide, netMHCstab$Peptide),]
  identical(netMHC_matrix$Peptide, netMHCstab$Peptide)
  
  ## Read in and format WT results
  netMHC_WT <- as.data.frame(read.table(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan_WT/", sample, "_netmhc_WT_9_10mer.xsl", sep=""), skip=1, header=TRUE))
  netMHC_WT <- netMHC_WT[-1,]
  netMHC_WT <- netMHC_WT[,which(colnames(netMHC_WT) %in% c("Peptide", "ID", "nM", "nM.1", "nM.2", "nM.3", "nM.4", "nM.5"))]
  ID <- str_split_fixed(netMHC_WT$ID, "_", 4)
  ID[,1] <- paste("chr", ID[,1], sep="")
  netMHC_WT$ID <- paste(ID[,1], ID[,2], sep=":")
  
  ## Read in and format CTL results
  netCTL <- as.data.frame(read.table(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netCTL/", sample, "_netctlpan.xsl", sep=""), header=TRUE, sep="\t"))
  netCTL_10mer <- as.data.frame(read.table(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netCTL/", sample, "_netctlpan_10mer.xsl", sep=""), header=TRUE, sep="\t"))
  netCTL <- rbind(netCTL, netCTL_10mer)
  ID <- str_split_fixed(netCTL$Sequence.Name, ":", 4)
  ID[,1] <- paste("chr", ID[,1], sep="")
  netCTL$ID <- paste(ID[,1], ID[,2], sep=":")
  
  ## Read in and format MHC class II results
  netMHCII_matrix <- as.data.frame(read.table(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan_classII/", sample, "_netmhcII.xsl", sep=""), skip=1, header=TRUE))
  netMHCII_matrix <- netMHCII_matrix[-which(netMHCII_matrix$Peptide %in% wt_all$V2),]
  ID <- str_split_fixed(netMHCII_matrix$ID, "_", 4)
  ID[,1] <- paste("chr", ID[,1], sep="")
  netMHCII_matrix$ID <- paste(ID[,1], ID[,2], sep=":")
  netMHCII_matrix <- netMHCII_matrix[!duplicated(netMHCII_matrix$Peptide),]
  
  ## Read in and process scrambled netMHC files
  netMHC_scrambled_1 <- process_netMHC(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/Scrambled_10_iterations/", sample, "_netmhc_scrambled_1.xsl", sep=""))
  netMHC_scrambled_2 <- process_netMHC(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/Scrambled_10_iterations/", sample, "_netmhc_scrambled_2.xsl", sep=""))
  netMHC_scrambled_3 <- process_netMHC(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/Scrambled_10_iterations/", sample, "_netmhc_scrambled_3.xsl", sep=""))
  netMHC_scrambled_4 <- process_netMHC(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/Scrambled_10_iterations/", sample, "_netmhc_scrambled_4.xsl", sep=""))
  netMHC_scrambled_5 <- process_netMHC(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/Scrambled_10_iterations/", sample, "_netmhc_scrambled_5.xsl", sep=""))
  netMHC_scrambled_6 <- process_netMHC(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/Scrambled_10_iterations/", sample, "_netmhc_scrambled_6.xsl", sep=""))
  netMHC_scrambled_7 <- process_netMHC(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/Scrambled_10_iterations/", sample, "_netmhc_scrambled_7.xsl", sep=""))
  netMHC_scrambled_8 <- process_netMHC(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/Scrambled_10_iterations/", sample, "_netmhc_scrambled_8.xsl", sep=""))
  netMHC_scrambled_9 <- process_netMHC(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/Scrambled_10_iterations/", sample, "_netmhc_scrambled_9.xsl", sep=""))
  netMHC_scrambled_10 <- process_netMHC(paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/netMHCpan/Scrambled_10_iterations/", sample, "_netmhc_scrambled_10.xsl", sep=""))

  
  # Find min binding for true binders and all scrambled binders
  for (i in 1:length(peptides$V1)){ 
    ################### ADD WT and MT binding #######################################################
    netMHC_subset <- netMHC[which(netMHC$ID==peptides$V5[i]),] ## identify relevant peptides
    netMHC_subset <- netMHC_subset[!duplicated(netMHC_subset$Peptide),]
    if (length(netMHC_subset$Peptide)!=0){
    netMHC_WT_subset <- netMHC_WT[which(netMHC_WT$ID==peptides$V5[i]),] ## idetnify relevant WT peptides
    distance_matrix <- stringdist::stringdistmatrix(netMHC_subset$Peptide, netMHC_WT_subset$Peptide, method="h") ## Calculate similarity all WT and MT peptides
    closest_matches <- apply(distance_matrix, 1, which.min) ## Find closest match
    netMHC_WT_matched <- netMHC_WT_subset[closest_matches,] ## Match on closest match
    peptides$min_binding[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5) ## Find min bindnig
    indices <- which(netMHC_subset == peptides$min_binding[i], arr.ind = TRUE) ## Find index for min binding
    peptides$WT_binding[i] <- as.numeric(netMHC_WT_matched[indices[1], indices[1,2]]) ## Add WT binding
    peptides$MT_9mer[i] <- netMHC_subset[indices[1],1]
    peptides$WT_matched[i] <- netMHC_WT_matched[indices[1],1]
    test <- stringdist::stringdist(netMHC_subset[indices[1],1], netMHC_WT_matched[indices[1],1]) ## Test that closest match matches
    if (test > 1){
      print("Warning, check match of WT")
    }
    
    ################### ADD stability scores #######################################################
    matching_stab <- netMHCstab[which(netMHCstab$Peptide==peptides$MT_9mer[i]),]
    peptides$max_stability[i] <- unique(matching_stab[,indices[1,2]])
    
    
    ################### ADD processing scores #######################################################
    netCTL_match <- netCTL[which(netCTL$Peptide==peptides$MT_9mer[i] & netCTL$ID==peptides$V5[i]),]
    peptides$Cle[i] <- max(netCTL_match$Cle)
    peptides$TAP[i] <- max(netCTL_match$TAP)
    
    ################### ADD classII scores #######################################################
    netMHCII_subset <- netMHCII_matrix[which(netMHCII_matrix$ID==peptides$V5[i]),] ## identify relevant peptides
    peptides$netMHC_II_binding[i] <- min(netMHCII_subset$nM, netMHCII_subset$nM.1, netMHCII_subset$nM.2, netMHCII_subset$nM.3,
                                         netMHCII_subset$nM.4, netMHCII_subset$nM.5, netMHCII_subset$nM.6, netMHCII_subset$nM.7,
                                         netMHCII_subset$nM.8, netMHCII_subset$nM.9, netMHCII_subset$nM.10, netMHCII_subset$nM.11, 
                                         netMHCII_subset$nM.12)
    indices <- which(netMHCII_subset == peptides$netMHC_II_binding[i], arr.ind = TRUE) ## Find index for min binding
    peptides$MHCII_peptide[i] <- netMHCII_subset[indices[1],2]
    if(length(netMHCII_subset$nM.13)>0){
      print("More HLA class II alleles not accounted for")
    }
    
    ################### ADD scrambled binding #######################################################
    netMHC_subset <- netMHC_scrambled_1[which(netMHC_scrambled_1$ID==peptides$V5[i]),]
    peptides$min_binding_scrambled_1[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5)
    netMHC_subset <- netMHC_scrambled_2[which(netMHC_scrambled_2$ID==peptides$V5[i]),]
    peptides$min_binding_scrambled_2[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5)
    netMHC_subset <- netMHC_scrambled_3[which(netMHC_scrambled_3$ID==peptides$V5[i]),]
    peptides$min_binding_scrambled_3[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5)
    netMHC_subset <- netMHC_scrambled_4[which(netMHC_scrambled_4$ID==peptides$V5[i]),]
    peptides$min_binding_scrambled_4[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5)
    netMHC_subset <- netMHC_scrambled_5[which(netMHC_scrambled_5$ID==peptides$V5[i]),]
    peptides$min_binding_scrambled_5[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5)
    netMHC_subset <- netMHC_scrambled_6[which(netMHC_scrambled_6$ID==peptides$V5[i]),]
    peptides$min_binding_scrambled_6[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5)
    netMHC_subset <- netMHC_scrambled_7[which(netMHC_scrambled_7$ID==peptides$V5[i]),]
    peptides$min_binding_scrambled_7[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5)
    netMHC_subset <- netMHC_scrambled_8[which(netMHC_scrambled_8$ID==peptides$V5[i]),]
    peptides$min_binding_scrambled_8[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5)
    netMHC_subset <- netMHC_scrambled_9[which(netMHC_scrambled_9$ID==peptides$V5[i]),]
    peptides$min_binding_scrambled_9[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5)
    netMHC_subset <- netMHC_scrambled_10[which(netMHC_scrambled_10$ID==peptides$V5[i]),]
    peptides$min_binding_scrambled_10[i] <- min(netMHC_subset$nM, netMHC_subset$nM.1, netMHC_subset$nM.2, netMHC_subset$nM.3, netMHC_subset$nM.4, netMHC_subset$nM.5)
    }
    if (length(netMHC_subset$Peptide)==0){
      print(paste("peptide", peptides$V5[i], "missing for", sample))
      peptides$MT_9mer[i] <- NA
    }
  }

  peptides <- peptides[which(!duplicated(peptides$MT_9mer)),]
  if (length(peptides[which(is.na(peptides$MT_9mer)),1])>0){
    peptides <- peptides[-which(is.na(peptides$MT_9mer)),]
  }
  
  write.csv(peptides, paste("~/3.0 Hasting Research/Immunoediting_human_work_with_new_samples/Immunogenicity/", sample, "_peptides_kd_stab.txt", sep=""))
}
else {print("File already exists")}
}
```